---

- name: install dependencies
  become: yes
  package:
    name:
      - git
      - ruby
      - ruby-devel
      - podman
      - podman-compose
      - "@development-tools"
      - curl
      - file
      - zlib-devel
      - libxcrypt-compat
      - gmp-devel
      - libbsd-devel
      - libedit-devel
      - libevent-devel
      - libxml2-devel
      - libyaml-devel
      - llvm-static
      - openssl-devel
      - redhat-rpm-config
      - llvm
    state: present

- name: install VS Code repo
  become: yes
  yum_repository:
    name: code
    description: Visual Studio Code repo
    file: vscode
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    gpgcheck: yes

- name: install VS Code
  become: yes
  package:
    name: "code-{{ visual_studio_code_version }}"
    state: present

- name: install bundler gem
  become: yes
  gem:
    name: bundler
    state: present

- name: install snapd
  become: yes
  package:
    name: snapd
    state: present

- name: enable snapd classic environment
  become: yes
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    owner: root
    group: root
    state: link

- name: Install crystal from snap
  become: yes
  snap:
    name: crystal
    classic: yes

